### ISSUE TITLE
Combination_Sum

### ISSUE THREAD

**Issue by ghost** [iphkwan/leetcode#2]
What if the candidates is [1, 1] and target is 1? Will duplicate results be returned?

**Comment by iphkwan** [comment]
@Marzy-ya Please review the code clearly.

**Comment by ghost** [comment]
@iphkwan I run your program on my computer and it returns duplicate results: [ [1], [1] ].

```
int main(){
    vector<int> v;
    v.push_back(1);
    v.push_back(1);
    vector<vector<int> > rst = Solution().combinationSum(v, 1);
    for (int i = 0; i < rst.size(); i++){
        for (int j = 0; j < rst[i].size(); j++)
            cout << rst[i][j] << " ";
        cout << endl;
    }
    return 0;
}
```

**Comment by iphkwan** [comment]
@Marzy-ya “The solution set must not contain duplicate combinations.” You can review the "Combination Sum II" for the remove-duplicate's solution.

**Comment by iphkwan** [comment]
@Marzy-ya My fault. You can do unique() first to handle this situation.
