### ISSUE TITLE
Populating_Next_Right_Pointers_in_Each_Node

### ISSUE THREAD

**Issue by ghost** [iphkwan/leetcode#3]
What is "constant extra space"? Does recursion use constant extra space?
I know in each recursion, your program uses constant extra space only. But the times of recursion is dependent on the level of the tree, can we still say the program uses constant extra space?
So, what is "constant extra space"?

**Comment by iphkwan** [comment]
@Marzy-ya yeah, i absolutely haven't noticed this constraint. You can write a non-recursive version using pointers to reach O(1) space. Just use father level lists to update current level.

**Comment by ghost** [comment]
Yeah, after reading your code, I can imagine an algorithm to satisfy the constraint. Thanks a lot!
