### ISSUE TITLE
能使用你在 Github 上 LeetCode 的题解吗？

### ISSUE THREAD

**Issue by Jeswang** [iphkwan/leetcode#4]
我做了一个 iOS 下的 LeetCode 客户端，想把你的题解放在应用里，可以吗？
- 会在应用的介绍里署上你的名字
- 把应用送你一份

**Comment by Teeeeeebag** [comment]
可以，随便用！

**Comment by zfu** [comment]
也送我一份把。

2014-10-05 10:06 GMT-04:00 Jesse Wang notifications@github.com:

> 我做了一个 iOS 下的 LeetCode 客户端，想把你的题解放在应用里，可以吗？
> - 会在应用的介绍里署上你的名字
> - 把应用送你一份
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/iphkwan/leetcode/issues/4.

## 

Best regards,

Zhigang Fu

**Comment by CodeOsiris** [comment]
可以

**Comment by xuchen509** [comment]
ok

2014-10-05 7:06 GMT-07:00 Jesse Wang notifications@github.com:

**Comment by Jeswang** [comment]
哈哈，都这么热情，知道了。

@iphkwan 如果有什么问题，或者不可以用请给我发邮件吧

**Comment by iphkwan** [comment]
@Jeswang Enjoy it.

**Comment by juege** [comment]
好的 。不过我的解题方法也不都是最优，有的也要修改。

------------------ 原始邮件 ------------------
发件人: "xuchen509"notifications@github.com; 
发送时间: 2014年10月6日(星期一) 凌晨0:47
收件人: "iphkwan/leetcode"leetcode@noreply.github.com; 
主题: Re: [leetcode] 能使用你在 Github 上 LeetCode 的题解吗？ (#4)

ok 

 2014-10-05 7:06 GMT-07:00 Jesse Wang notifications@github.com:

**Comment by Jeswang** [comment]
上午把文件名处理了一下，发现了两处拼写错误：

"recorder-list": "reorder-list"
"maximun-depth-of-binary-tree": "maximum-depth-of-binary-tree"

**Comment by Jeswang** [comment]
![ios simulator screen shot oct 6 2014 4 08 38 pm](https://cloud.githubusercontent.com/assets/553783/4522917/81ccbcdc-4d30-11e4-9dc5-741e961c817a.png)

加得差不多了，大概就是这样子在代码里有署名来源是这里。

**Comment by zfu** [comment]
可以用。 谢谢。记得让我也用用IOS版的

2014-10-05 10:06 GMT-04:00 Jesse Wang notifications@github.com:

> 我做了一个 iOS 下的 LeetCode 客户端，想把你的题解放在应用里，可以吗？
> - 会在应用的介绍里署上你的名字
> - 把应用送你一份
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/iphkwan/leetcode/issues/4.

## 

Best regards,

Zhigang Fu
